const data = {
  products: [
    {
      id: "1",
      name: "Jean Jacket",
      category: "Jackets",
      image: "../public/images/product1.jpg",
      price: 100,
      brand: "Levi",
      rating: 4.0,
      numReviews: 10,
      description: "Great and warm!",
    },
    {
      id: "2",
      name: "Jean Pants",
      category: "Bottoms",
      image: "public/images/product2.jpg",
      price: 75,
      brand: "Levi",
      rating: 5.0,
      numReviews: 5,
      description: "Durable pants!",
    },
    {
      id: "3",
      name: "Leather Jacket",
      category: "Jackets",
      image: "public/images/product3.jpg",
      price: 70,
      brand: "Levi",
      rating: 4.5,
      numReviews: 1,
      description: "Stylish and practical!",
    },
    {
      id: "4",
      name: "Leather Boots",
      category: "Shoes",
      image: "public/images/product4.jpg",
      price: 65,
      brand: "Levi",
      rating: 4.0,
      numReviews: 3,
      description: "Comfortable!",
    },
    {
      id: "5",
      name: "Leather Belt",
      category: "Accessories",
      image: "public/images/product5.jpg",
      price: 25,
      brand: "Levi",
      rating: 4.5,
      numReviews: 5,
      description: "Durable!",
    },
  ],
};

export default data;
